/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        System.out.println(new Triangle().classify(2, 3, 3));
    }
}
